### ISSUE TITLE
Request: Update to the latest version 1.5.3

### ISSUE THREAD

**Issue by Jarsky** [dantebarba/docker-autoremove-torrents#1]
Hey!

Thank you for providing this in a docker build! I have this running in my automation setup and it runs great. 
Looking at the configuration in this build vs the latest build, I think theres been a fair number of changes since this made. 

Was wondering if you can put together an updated build based on the January 22nd 1.5.3 release?
https://pypi.org/project/autoremove-torrents/1.5.3/

**Comment by jt196** [comment]
@Jarsky it's a pretty straightforward docker build. 

1. Clone the project directory into a folder of your choice
2. While in the project folder, run `docker build -t auto-remove-torrents:latest .` 

It'll take a little while to build the image but if you look at the Dockerfile, it pulls the latest project from GitHub: 

`ARG GIT_REPO='https://github.com/dantebarba/autoremove-torrents.git'`

I created a _docker-compose.yml_ file, and added the _cron.sh_ and _config.yml_ files to that folder, then mount them. 

```YML
version: '3.3'
services:
    auto-remove-torrents:
        container_name: auto-remove-torrents
        restart: always
        environment:
            - PUID=$YOUR_USER_ID
            - PGID=$YOUR_GROUP_ID
            - TZ=Europe/London
        volumes:
            - '/path/to/your/docker/folder/config:/app'
        image: auto-remove-torrents:latest
```

Then run `docker-compose up -d` in the folder and it should run just fine.
